# Generated by Django 5.0.6 on 2026-09-11 05:18

import apps.resumes.models
import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        pgvector.django.VectorExtension(),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.resumes.models.resume_upload_path)),
                ('raw_text', models.TextField(blank=True)),
                ('parsed_data', models.JSONField(blank=True, null=True)),
                ('parse_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('parsed', 'Parsed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('parse_error', models.TextField(blank=True)),
                ('embedding', pgvector.django.VectorField(blank=True, dimensions=1536, null=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
