# Generated by Django 5.0.6 on 2026-09-11 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('evaluated', 'Evaluated')], default='generated', max_length=16)),
                ('difficulty', models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior')], default='mid', max_length=16)),
                ('focus_areas', models.JSONField(blank=True, default=list, help_text='Skills this interview targets')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('type', models.CharField(choices=[('coding', 'Coding'), ('system_design', 'System design'), ('conceptual', 'Conceptual'), ('behavioral', 'Behavioral')], max_length=16)),
                ('prompt', models.TextField()),
                ('rubric', models.JSONField(blank=True, default=dict, help_text='LLM-generated grading rubric: key points, ideal answer')),
                ('candidate_answer', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviews.interview')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
