# Generated by Django 5.0.6 on 2026-09-11 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(help_text='0-100 automated composite score')),
                ('recommendation', models.CharField(choices=[('strong_hire', 'Strong hire'), ('hire', 'Hire'), ('borderline', 'Borderline'), ('no_hire', 'No hire')], max_length=20)),
                ('per_question_scores', models.JSONField(default=list, help_text='[{question_id, score, feedback}]')),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('summary', models.TextField(blank=True)),
                ('reviewed_by_human', models.BooleanField(default=False)),
                ('human_override_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='interviews.interview')),
            ],
        ),
    ]
